# Dependencies
markdown:         redcarpet
highlighter:         pygments

# Permalinks
permalink:        /:title/

gems: [jekyll-paginate]

# Setup
title:            "@clrh"
tagline:          'Claire Hernandez'
description:      ""
url:              http://clrh.github.io
baseurl:          /

author:
  name:           'clrh'
  twitter:        http://twitter.com/clrh
  github:         'clrh'

paginate:         5

# Custom vars
version:          2.1.0
theme: jekyll-theme-hydeout


